[colors.primary]
background = '#111415'
foreground = '#e1e2e4'
 
[colors.cursor]
text = '#e1e2e4'
cursor = '#c0c8cd' 
 
[colors.vi_mode_cursor]
text = '#111415'
cursor = '#64d3ff' 
 
[colors.search.matches]
foreground = '#40484c' 
background = '#c6c2ea' 
 
[colors.search.focused_match]
foreground = '#40484c' 
background = '#64d3ff' 
 
[colors.footer_bar]
foreground = '#40484c' 
background = '#e1e2e4' 
 
[colors.hints.start]
foreground = '#40484c' 
background = '#b4cad6' 
 
[colors.hints.end]
foreground = '#40484c' 
background = '#b4cad6' 
 
[colors.selection]
text = '#111415'
background = '#64d3ff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#64d3ff' 
yellow = '#006783' 
blue = '#64d3ff' 
magenta = '#c6c2ea' 
cyan = '#b4cad6' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 